#!/usr/bin/env bash

if [ -z "${INSIGHTEDGE_HOME}" ]; then
  export INSIGHTEDGE_HOME="$(cd "`dirname "$0"`"/..; pwd)"
fi

# disable randomized hash for string in Python 3.3+
export PYTHONHASHSEED=0

# add datagrid and InsightEdge JARs to job --jars
DATAGRID_LOCATION="${INSIGHTEDGE_HOME}/datagrid"
INSIGHTEDGE_JAR_LOCATION="$(find ${INSIGHTEDGE_HOME}/lib -name "insightedge-core-*.jar")"
GS_SCALA_JAR_LOCATION="$(find ${INSIGHTEDGE_HOME}/lib -name "gigaspaces-scala-*.jar")"
GS_JARS=$(echo $DATAGRID_LOCATION/lib/required/*.jar | tr ' ' ',')
GS_JARS="$GS_JARS,$INSIGHTEDGE_JAR_LOCATION,$GS_SCALA_JAR_LOCATION"

process_args(){
    ARGUMENTS=""
    for i in "$@"
        do
            if [[ $i == "--jars" ]]; then
                ARGUMENTS+="--jars $GS_JARS,"
            else ARGUMENTS+="$i "
            fi
        done
    if [[ ! $ARGUMENTS =~ .*--jars.* ]]
    then
       ARGUMENTS=" --jars $GS_JARS $ARGUMENTS"
    fi
    echo $ARGUMENTS
}
ARGS=$(process_args "$@")

exec "${INSIGHTEDGE_HOME}"/bin/insightedge-class org.apache.spark.deploy.SparkSubmit $ARGS
